services:
  shell:
    container_name: "meridiem-shell"
    image: "darrenedale/equit:php-8.3-cli"
    volumes:
      - "./:/meridiem"
    working_dir: "/meridiem"
    stdin_open: true
    tty: true
    environment:
      PHP_IDE_CONFIG: serverName=meridiem-docker
      XDEBUG_CONFIG: "client_host=xdebug-client"
      XDEBUG_SESSION: 1
    extra_hosts:
      - "xdebug-client:host-gateway"
